"""Generate the explicit Cabello-33 Weyl-Heisenberg orbit in C^3.

Reference: A. Cabello, "Simplest Kochen-Specker Set",
Phys. Rev. Lett. 135, 190203 (2025); arXiv:2508.07335.

Construction:
- Weyl-Heisenberg generators in C^3:
    X = cyclic shift  (e_i -> e_{i+1 mod 3})
    Z = diag(1, w, w^2),  w = e^{2 pi i / 3}
- Cabello specifies 14 bases (5 for Alice, 9 for Bob) generated by
  X, Z^2 acting on a seed set.
- The union of all basis vectors yields 33 distinct rays (projectively).

This script enumerates the orbit, canonicalises rays, and verifies:
  (a) all 33 rays have coordinates in {0, +/-1, +/-w, +/-w^2} = {0} U mu_6
  (b) the orthogonality graph has 78 pairs
  (c) the set is KS-uncolorable (SAT cross-check)
  (d) outputs a LaTeX-ready table.
"""
import sys
import math
import cmath
from fractions import Fraction
from itertools import product

sys.stdout.reconfigure(line_buffering=True)

# Primitive cube root of unity in exact (a, b) form  (a + b*omega)
# Represent each Eisenstein integer as a tuple (a, b) of Python ints,
# meaning a + b*omega where omega^2 = -1 - omega.
def eis(a, b):
    return (int(a), int(b))

ZERO = eis(0, 0)
ONE = eis(1, 0)
OMEGA = eis(0, 1)
OMEGA2 = eis(-1, -1)        # omega^2 = -1 - omega
NEG_ONE = eis(-1, 0)
NEG_OMEGA = eis(0, -1)
NEG_OMEGA2 = eis(1, 1)

EISENSTEIN_UNITS = {ONE, OMEGA, OMEGA2, NEG_ONE, NEG_OMEGA, NEG_OMEGA2}
S6_ALPHABET = EISENSTEIN_UNITS | {ZERO}


def eis_add(p, q):
    return (p[0] + q[0], p[1] + q[1])


def eis_neg(p):
    return (-p[0], -p[1])


def eis_mul(p, q):
    # (a + b w)(c + d w) = ac + (ad + bc) w + bd w^2
    # = ac + (ad + bc) w + bd (-1 - w)
    # = (ac - bd) + (ad + bc - bd) w
    a, b = p
    c, d = q
    return (a * c - b * d, a * d + b * c - b * d)


def eis_conj(p):
    # conjugate(a + b w) = a + b w^2 = a + b(-1 - w) = (a - b) + (-b) w
    a, b = p
    return (a - b, -b)


def eis_to_complex(p):
    a, b = p
    w = cmath.exp(2j * cmath.pi / 3)
    return a + b * w


def eis_abs2(p):
    # |a + b w|^2 = a^2 - a b + b^2  (since w + wbar = -1, w*wbar = 1)
    a, b = p
    return a * a - a * b + b * b


def hermitian_dot(v, w):
    """Hermitian inner product <v|w> = sum conj(v_i) * w_i."""
    return [eis_mul(eis_conj(vi), wi) for vi, wi in zip(v, w)]


def vec_eq_zero(v):
    return all(c == ZERO for c in v)


def sum_eis(terms):
    s = ZERO
    for t in terms:
        s = eis_add(s, t)
    return s


def is_orthogonal(v, w):
    return sum_eis(hermitian_dot(v, w)) == ZERO


def canonicalize_ray(v):
    """Return a canonical representative of the ray spanned by v.

    Strategy: find first nonzero coordinate; if it is an Eisenstein unit,
    multiply through by its inverse so that the first nonzero coord is 1.
    For non-unit first coord, normalise the leading coord by its sign
    convention and leave it; we rely on the orbit producing only
    unit-first-coord rays for Cabello's set."""
    v = tuple(v)
    if vec_eq_zero(v):
        return None

    # Find first nonzero coordinate
    pivot_idx = None
    for i, c in enumerate(v):
        if c != ZERO:
            pivot_idx = i
            break

    pivot = v[pivot_idx]
    # If pivot is a unit, divide through
    if pivot in EISENSTEIN_UNITS:
        inv = unit_inverse(pivot)
        return tuple(eis_mul(inv, c) for c in v)
    # Otherwise return as-is (caller can decide)
    return v


def unit_inverse(u):
    """Multiplicative inverse of an Eisenstein unit."""
    # Units: 1, -1, w, -w, w^2, -w^2
    # 1*1 = 1; (-1)*(-1) = 1; w*w^2 = 1; (-w)*(-w^2) = 1
    table = {
        ONE: ONE,
        NEG_ONE: NEG_ONE,
        OMEGA: OMEGA2,
        OMEGA2: OMEGA,
        NEG_OMEGA: NEG_OMEGA2,
        NEG_OMEGA2: NEG_OMEGA,
    }
    return table[u]


# -----------------------------------------------------------------
# Weyl-Heisenberg construction
# -----------------------------------------------------------------
# X: cyclic shift  X e_i = e_{(i+1) mod 3}
# Z: diag(1, w, w^2)
# As matrices acting on column vectors v in C^3.

def apply_X(v):
    # X (a,b,c) = (c,a,b)  (cyclic shift: row i gets entry (i-1 mod 3))
    return (v[2], v[0], v[1])


def apply_Z(v):
    return (v[0], eis_mul(OMEGA, v[1]), eis_mul(OMEGA2, v[2]))


def apply_powers(v, x_power, z_power):
    w = v
    for _ in range(x_power % 3):
        w = apply_X(w)
    for _ in range(z_power % 3):
        w = apply_Z(w)
    return w


# -----------------------------------------------------------------
# Cabello's bases (from arXiv:2508.07335 v3, Eqs. 1a-1e and 2a-2i)
# Five Alice bases + nine Bob bases, but the union is 14 bases
# producing 33 distinct rays.  We seed from a small generating set
# and close under the WH group.
# -----------------------------------------------------------------

# The Alice basis x=0 is the standard basis (axis triad).
# The Alice basis x=1 is { (1,w,w^2), (1,1,1), (w^2,w,1) }.
# We use these as a seed and close under X, Z^2.

# Yu-Oh (PRL 2012) 13-ray state-dependent contextuality set.
# All coordinates are real integers, but their WH-orbit fills out
# the Cabello 33-vector KS set in C^3.
SEED_RAYS = [
    # 3 axis rays
    (ONE, ZERO, ZERO),
    (ZERO, ONE, ZERO),
    (ZERO, ZERO, ONE),
    # 6 face-diagonal "y" rays
    (ONE, ONE, ZERO),
    (ONE, NEG_ONE, ZERO),
    (ONE, ZERO, ONE),
    (ONE, ZERO, NEG_ONE),
    (ZERO, ONE, ONE),
    (ZERO, ONE, NEG_ONE),
    # 4 body-diagonal "h" rays
    (ONE, ONE, ONE),
    (ONE, ONE, NEG_ONE),
    (ONE, NEG_ONE, ONE),
    (NEG_ONE, ONE, ONE),
]


def orbit_close(seed_rays):
    """Close the seed set under X, Z, Z^2 (the WH group acts on rays)."""
    seen = set()
    queue = []
    for r in seed_rays:
        canon = canonicalize_ray(r)
        if canon is not None and canon not in seen:
            seen.add(canon)
            queue.append(canon)
    ops = [apply_X, apply_Z]
    i = 0
    while i < len(queue):
        v = queue[i]
        for op in ops:
            w = op(v)
            cw = canonicalize_ray(w)
            if cw is not None and cw not in seen:
                seen.add(cw)
                queue.append(cw)
        i += 1
    return queue


# -----------------------------------------------------------------
# Run construction
# -----------------------------------------------------------------

orbit = orbit_close(SEED_RAYS)
print(f"Orbit size after closing under X, Z: {len(orbit)}")

# Verify all rays have coordinates in S_6 alphabet
not_in_s6 = []
for v in orbit:
    for c in v:
        if c not in S6_ALPHABET:
            not_in_s6.append((v, c))
            break

print(f"Rays with all coordinates in S_6 alphabet: {len(orbit) - len(not_in_s6)}/{len(orbit)}")
if not_in_s6:
    print("  Exceptions:")
    for v, c in not_in_s6[:5]:
        print(f"    {v}  (bad coord: {c})")

# Orthogonality graph
pairs = []
adj = {i: set() for i in range(len(orbit))}
for i in range(len(orbit)):
    for j in range(i + 1, len(orbit)):
        if is_orthogonal(orbit[i], orbit[j]):
            pairs.append((i, j))
            adj[i].add(j)
            adj[j].add(i)

print(f"Orthogonal pairs: {len(pairs)}")

# Find all triads
triads = []
for i in range(len(orbit)):
    nbrs = sorted(adj[i])
    for idx_j, j in enumerate(nbrs):
        if j <= i:
            continue
        for k in nbrs[idx_j + 1:]:
            if k <= j:
                continue
            if k in adj[j]:
                triads.append((i, j, k))
print(f"Orthogonal triads (potential bases): {len(triads)}")

# SAT KS-uncolorability check
try:
    from pysat.solvers import Glucose4
    solver = Glucose4()
    n = len(orbit)
    for a, b, c in triads:
        va, vb, vc = a + 1, b + 1, c + 1
        solver.add_clause([va, vb, vc])
        solver.add_clause([-va, -vb])
        solver.add_clause([-va, -vc])
        solver.add_clause([-vb, -vc])
    for i, j in pairs:
        vi, vj = i + 1, j + 1
        solver.add_clause([-vi, -vj])
    sat_result = solver.solve()
    solver.delete()
    print(f"SAT result: {'COLORABLE' if sat_result else 'KS-UNCOLORABLE'}")
except ImportError:
    print("PySAT not available; skipping SAT check")

# -----------------------------------------------------------------
# LaTeX table output
# -----------------------------------------------------------------

def eis_to_tex(p):
    a, b = p
    # a + b*omega in shortest TeX form
    if (a, b) == (0, 0):
        return "0"
    if (a, b) == (1, 0):
        return "1"
    if (a, b) == (-1, 0):
        return "-1"
    if (a, b) == (0, 1):
        return r"\omega"
    if (a, b) == (0, -1):
        return r"-\omega"
    if (a, b) == (-1, -1):
        return r"\omega^2"
    if (a, b) == (1, 1):
        return r"-\omega^2"
    # general fallback
    return f"({a}, {b})_w"


print()
print("=" * 70)
print("LaTeX table of 33 rays (one row per ray)")
print("=" * 70)
for idx, v in enumerate(orbit, start=1):
    tex = "(" + ", ".join(eis_to_tex(c) for c in v) + ")"
    print(f"  {idx:2d} & {tex}  \\\\")

print()
print("=" * 70)
print("LaTeX listing of triads (orthogonal bases)")
print("=" * 70)
for tno, (i, j, k) in enumerate(triads, start=1):
    print(f"  B_{{{tno}}} & \\{{{i+1}, {j+1}, {k+1}\\}}  \\\\")
