"""Send cyclotomic_letter.tex to GPT-5.4-pro for aggressive Oxford-style challenge review."""
import requests
import re
import sys
from datetime import datetime
from pathlib import Path

# Read API key
api_key = None
for line in Path(r"D:\Blockchain-Backups\Keystores\API-Keys\api-keys-master.txt").read_text(encoding="utf-8").splitlines():
    if "sk-svcacct-" in line:
        for part in line.strip().split():
            if part.startswith("sk-svcacct-"):
                api_key = part
                break
        if api_key:
            break

if not api_key:
    print("ERROR: Could not find OpenAI service account API key")
    sys.exit(1)

print(f"API key: {api_key[:30]}...")

tex_path = Path(r"C:\Users\Michael Kernaghan\contextuality\paper\cyclotomic_letter.tex")
tex = tex_path.read_text(encoding="utf-8")

# Strip LaTeX commands for readability (keep math as-is; reviewers cope with TeX math)
text = tex
text = re.sub(r"\\documentclass.*?\\begin\{document\}", "", text, flags=re.DOTALL)
text = re.sub(r"\\end\{document\}", "", text)
for cmd in ["textbf", "textit", "emph", "texttt", "mathrm", "mathbb", "mathcal"]:
    pattern = "\\\\" + cmd + r"\{([^}]*)\}"
    text = re.sub(pattern, r"\1", text)
text = re.sub(r"\\cite\{([^}]*)\}", r"[cite:\1]", text)
text = re.sub(r"\\ref\{([^}]*)\}", r"[ref:\1]", text)
text = re.sub(r"\\label\{[^}]*\}", "", text)
text = re.sub(r"\\url\{([^}]*)\}", r"\1", text)
text = re.sub(r"\\\\", " ", text)
text = re.sub(r"\n{3,}", "\n\n", text)

if len(text) > 80000:
    text = text[:80000] + "\n\n[TRUNCATED]"

word_count = len(text.split())
print(f"Extracted {word_count} words from LaTeX ({len(text)} chars)")

prompt = r"""You are conducting an AGGRESSIVE Oxford-style challenge review of a Physical Review Letters submission in quantum foundations and algebraic combinatorics.

The paper's central claim: the ray set S_n generated by nth roots of unity in C^3 is Kochen-Specker uncolorable iff 6 | n. Sufficiency reduces to Cabello's 33-vector Eisenstein KS set in S_6. Necessity is via a three-case vanishing-sum analysis of orthogonalities among rays whose coordinates are nth roots of unity (or zero).

Adopt the stance of an unsympathetic Oxford DPhil examiner who has read the cited literature and is hunting for grounds to reject. Do NOT be polite. Do NOT pad. Be specific to THIS paper.

Complete ALL FOUR steps thoroughly. Reference lemmas, equations, and lines verbatim when attacking.

STEP 1 -- HOSTILE EXAMINER (proof scrutiny):
Identify the 4 weakest steps in the proof, ranked by how hard they would be to fix. Force yourself to look at:
- Lemma 1 (three-term vanishing sums): the casework "If a = b ... similarly for other coincidences" -- is the "similarly" actually trivial, or is a case being elided? Is the equilateral-triangle argument fully rigorous over C, including non-primitive cases?
- Lemma 3 (no all-nonzero ray in any triad when 3 nmid n): the step "any vector orthogonal to both [r1, r2] must lie ... in the k-axis" silently assumes r1 and r2 are linearly independent. Is independence established? What if the two one-zero rays are projectively distinct but coplanar in a degenerate way?
- Case 3 (projective collapse, Lemma 5): the count "n^2 all-nonzero rays partition into n^2/3 isolated triads" presupposes 3 | n^2 when 3 | n -- fine -- but does the proof exclude that an all-nonzero ray could lie in more than one triad via some non-T_+ orthogonality? Lemma 4 says exactly two orthogonal neighbours, but is the uniqueness of the triad (Lemma 5) actually equivalent, or is there a gap when w_+ and w_- coincide projectively in edge cases?
- The "monotone" sufficiency argument ("any superset of an uncolorable set is uncolorable") -- is this trivially true for KS uncolourability, or does it require the superset's orthogonality structure to restrict to the subset's? The relevant statement is about ray sets, not graphs; spell out whether new orthogonalities in S_n \ S_6 could "rescue" a coloring of S_6's vectors viewed inside S_n.

STEP 2 -- LITERATURE CHECK:
Check each citation against what the cited works actually establish:
- Cabello 2025 (arXiv:2508.07335) -- the paper invokes a 33-vector Eisenstein KS set as a black box. Is this set actually proven KS-uncolourable in Cabello, or is it numerically verified? Is "simplest by fewest bases" Cabello's framing or this author's? Is the set inside S_6 in the precise sense used here (coordinate alphabet, projective equivalence)?
- Cortez-Morales-Reyes 2022 (arXiv:2211.13216) -- the paper repeatedly insists its result is "logically independent" of theirs but also "consistent" and "agrees that primes 2 and 3 are both necessary". Is this hedge defensible? Could the two results be mutually derivable via a translation the author has not noticed?
- Lam-Leung 2000 -- is the cited classification actually needed at the 3-term level, or is the author over-citing a heavy result for an elementary case (the equilateral-triangle calculation in Lemma 1)?
- TsoukalasNexus2026, Schwartz2026 -- are these load-bearing references or window dressing for the AI-workflow narrative? Do they belong in a PRL bibliography?

STEP 3 -- PHILOSOPHY OF SCIENCE / FRAMING:
- Is the result a theorem about a parameterised family, or a phenomenon? The paper sometimes frames it as a "characterisation" and sometimes as a "factorisation 6 = 2 x 3 mechanism". Which is it, and does the prose oversell the latter?
- The "verification methodology" paragraph names 6 rounds of adversarial LLM review and PySAT cross-checks for n <= 100. Does this strengthen or weaken the paper? Would a PRL referee find the LLM provenance acceptance-positive, neutral, or grounds for concern?
- The Lean formalisation paragraph claims "sorry-free modulo a single cited fact" (Cabello's set). Is offloading the hardest combinatorial step to "Cabello says so" intellectually honest, or does it gut the formalisation claim?
- The Discussion floats generalisation to "Gaussian or quadratic integer alphabets". Is this a serious research signpost or speculative filler?

STEP 4 -- PRL FIT (publication judgement):
- Is the result PRL-worthy or better suited to J. Math. Phys. / Foundations of Physics?
- Is the title overclaiming? "requires exactly 6 | n" is strong; is the converse fully equally established compared to sufficiency?
- Are there missing controls a referee would demand (e.g., a worked numerical example for the smallest non-trivial case in each of Cases 1, 2, 3)?

OUTPUT FORMAT:
1. Up-front verdict: ACCEPT / MAJOR REVISION / MINOR REVISION / REJECT, with one-line justification.
2. A table of actionable issues: columns | Priority (High/Med/Low) | Step (1/2/3/4) | Issue (be specific, quote the paper) | Suggested Fix |.
3. A free-form "what I would tell the author over a glass of port" paragraph, blunt and constructive.

Do not flatter the author. Do not equivocate. If a section is solid, say it once and move on.

THE PAPER:

"""

print("Sending to GPT-5.4-pro via Responses API (this may take several minutes)...")

response = requests.post(
    "https://api.openai.com/v1/responses",
    headers={
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    },
    json={
        "model": "gpt-5.4-pro",
        "input": prompt + text,
    },
    timeout=900,
)

if response.status_code != 200:
    print(f"ERROR: API returned {response.status_code}")
    print(response.text[:2000])
    sys.exit(1)

data = response.json()

review = ""
for item in data.get("output", []):
    if item.get("type") == "message":
        for content_block in item.get("content", []):
            if content_block.get("type") == "output_text":
                review += content_block.get("text", "")

if not review:
    import json
    print("WARNING: No review text found. Raw response:")
    print(json.dumps(data, indent=2)[:3000])
    sys.exit(1)

usage = data.get("usage", {})

timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
outpath = Path(r"C:\Users\Michael Kernaghan\claude-inbox\peer-reviews") / f"cyclotomic_letter-oxford-gpt54-{timestamp}.txt"
outpath.parent.mkdir(parents=True, exist_ok=True)
with open(outpath, "w", encoding="utf-8") as f:
    f.write("Oxford Aggressive Challenge Review: cyclotomic_letter.tex\n")
    f.write(f"Source: {tex_path}\n")
    f.write(f"Date: {datetime.now().isoformat()}\n")
    f.write("Reviewer: GPT-5.4-pro (Oxford 4-step aggressive method)\n")
    f.write(f"Tokens: {usage.get('input_tokens', '?')} input, {usage.get('output_tokens', '?')} output\n")
    f.write("=" * 80 + "\n\n")
    f.write(review)

print(f"\nTokens: {usage.get('input_tokens', '?')} input, {usage.get('output_tokens', '?')} output")
print(f"Review saved to: {outpath}")
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
print(f"\n{'='*80}")
print(review)
print(f"{'='*80}")
