"""Send cyclotomic_letter.tex to GPT-5.2 for peer review."""
import requests
import re
import sys
from datetime import datetime
from pathlib import Path

# Read API key
api_key = None
for line in Path(r"E:\Blockchain-Backups\Keystores\API-Keys\api-keys-master.txt").read_text(encoding="utf-8").splitlines():
    if line.strip().startswith("API Key: sk-proj-"):
        api_key = line.strip().split("API Key: ")[1]
        break

if not api_key:
    print("ERROR: Could not find OpenAI API key")
    sys.exit(1)

print(f"API key: {api_key[:25]}...")

# Read the paper
with open(r"C:\Users\Michael Kernaghan\contextuality\paper\cyclotomic_letter.tex", "r", encoding="utf-8") as f:
    tex = f.read()

# Strip LaTeX commands for readability
text = tex
text = re.sub(r"\\documentclass.*?\\begin\{document\}", "", text, flags=re.DOTALL)
text = re.sub(r"\\end\{document\}", "", text)
for cmd in ["textbf", "textit", "emph", "texttt", "mathrm", "mathbb", "mathcal"]:
    pattern = "\\\\" + cmd + r"\{([^}]*)\}"
    text = re.sub(pattern, r"\1", text)
text = re.sub(r"\\cite\{[^}]*\}", "[ref]", text)
text = re.sub(r"\\ref\{[^}]*\}", "[ref]", text)
text = re.sub(r"\\label\{[^}]*\}", "", text)
text = re.sub(r"\\url\{([^}]*)\}", r"\1", text)
text = re.sub(r"\\\\", " ", text)
text = re.sub(r"\n{3,}", "\n\n", text)

# Truncate if too long
if len(text) > 60000:
    text = text[:60000] + "\n\n[TRUNCATED]"

word_count = len(text.split())
print(f"Extracted {word_count} words from LaTeX ({len(text)} chars)")

prompt = """You are an expert peer reviewer in quantum foundations, contextuality theory, and algebraic number theory.

Please provide a detailed peer review of this PRL-style letter. The paper proves that the ray set generated by nth roots of unity in C^3 is Kochen-Specker uncolorable if and only if 6|n.

Key claims to evaluate:
- The theorem: S_n is KS-uncolorable iff 6|n (complete algebraic proof, no computational evidence needed)
- Sufficiency: Cabello's Eisenstein 33-set embeds when 6|n
- Necessity Case 1 (odd n, 3 does not divide n): only axis triad, trivially colorable
- Necessity Case 2 (3 does not divide n, 2|n): perfect matching on plane orthogonality graph, explicit coloring
- Necessity Case 3 (3|n, odd n): projective collapse (6 permutations -> 2 rays via even/odd cosets), triad isolation, decomposable coloring
- Connection to Cortez-Morales-Reyes Z[1/6] minimality result
- Seven lemmas: 3-term vanishing sums, 2-term vanishing sums, perfect matching, plane independence, projective collapse, triad uniqueness, one-zero isolation

Structure your review as:
1. Summary (2-3 sentences)
2. Strengths (bulleted)
3. Weaknesses (bulleted)
4. Novelty Assessment (detailed)
5. Rigor Assessment (detailed - check each lemma and proof carefully)
6. Completeness Assessment (detailed)
7. Specific Suggestions for Improvement
8. Minor Issues
9. Overall Recommendation (Accept / Minor Revision / Major Revision / Reject) with justification

Be honest and critical. Check the mathematical proofs carefully. Do not inflate the contribution."""

print("Submitting to GPT-5.2...")

response = requests.post(
    "https://api.openai.com/v1/chat/completions",
    headers={
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    },
    json={
        "model": "gpt-5.2",
        "max_completion_tokens": 6000,
        "messages": [
            {"role": "system", "content": prompt},
            {"role": "user", "content": f"Paper text:\n\n{text}"},
        ],
    },
    timeout=300,
)

if response.status_code != 200:
    print(f"ERROR: {response.status_code}")
    print(response.text[:1000])
    sys.exit(1)

result = response.json()
review_text = result["choices"][0]["message"]["content"]
usage = result.get("usage", {})
print(f"Tokens: {usage.get('total_tokens', 'unknown')}")

# Save
timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
outdir = Path(r"C:\Users\Michael Kernaghan\claude-inbox\peer-reviews")
outdir.mkdir(parents=True, exist_ok=True)
outpath = outdir / f"cyclotomic_letter-review-{timestamp}.txt"

with open(outpath, "w", encoding="utf-8") as f:
    f.write("Peer Review: Kochen-Specker uncolorability in cyclotomic fields requires exactly 6|n\n")
    f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    f.write(f"Reviewer: GPT-5.2 (via OpenAI API)\n")
    f.write(f"Tokens: {usage.get('total_tokens', 'unknown')}\n")
    f.write("---\n\n")
    f.write(review_text)

print(f"\nReview saved to: {outpath}")
print(f"\n{'='*60}")
print(review_text)
